name: Bug
description: File a bug report
body:
  - type: markdown
    attributes:
      value: |
        Before opening a bug report, please see if a similar issue has been opened already.
        ---
        Thank you for taking the time to file a bug report. To address this bug as fast as possible, we need some information.
  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: "Which operating system do you use?"
      options:
        - Linux
        - Windows
        - MacOS
    validations:
      required: true
  - type: input
    id: appver
    attributes:
      label: App Version
      description: "What version of the app are you using? Please also indicate if it's a BETA or Release version"
      placeholder: "2.0.2 beta"
    validations:
      required: true
  - type: textarea
    id: report
    attributes:
      label: Detailed Description
      description: "Please provide a detailed description of the bug you have encountered"
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Reproducing the issue
      description: "Please list the steps you have taken to find the bug"
    validations:
      required: true
  - type: textarea
    id: additional
    attributes:
      label: Any additional info
      description: "If you'd like to include any additional information, please supply it here"
    validations:
      required: false
